apiVersion: v1
kind: Service
metadata:
  name: pablo-mysql
  namespace: kubeflow
  labels:
    app: pablo-mysql
spec:
  type: ClusterIP
  ports:
    - port: 3306
      protocol: TCP
      name: dbapi
  selector:
    app: pablo-mysql
