apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  # References:
  # * https://github.com/argoproj/argo-workflows/blob/v2.12.9/config/config.go
  # * https://github.com/argoproj/argo-workflows/blob/v2.12.9/docs/workflow-controller-configmap.md
  # * https://github.com/argoproj/argo-workflows/blob/v2.12.9/docs/workflow-controller-configmap.yaml

  # pns executor is a more portable default, see https://github.com/kubeflow/pipelines/issues/1654.
  # However, it is flaky for containers that run really fast, see https://github.com/kubeflow/pipelines/issues/5285.
  # So we still default to docker for now.
  containerRuntimeExecutor: pns
  persistence: |
    connectionPool:
      maxIdleConns: 100
      maxOpenConns: 0
      connMaxLifetime: 0s # 0 means connections don't have a max lifetime
    nodeStatusOffLoad: true
    clusterName: default
    mysql:
     host: pablo-mysql
     port: 3306
     database: argo
     tableName: argo_workflows
     userNameSecret:
        name: argo-mysql-config
        key: username
     passwordSecret:
        name: argo-mysql-config
        key: password
